// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uczbqvxdhlnjatgqoynf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjemJxdnhkaGxuamF0Z3FveW5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjczMDA4NDUsImV4cCI6MjA4Mjg3Njg0NX0.nUh3bzfmrGtd36j1HBy6ZG1j7tiqxZbqlO86EGMdKE8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});