import type { Juror } from './types';

export const JURY_POOL: Juror[] = [
  { id: 1, name: 'Juror #1', age: 55, occupation: 'Dentist', background: 'Owns a private clinic, values procedure and documentation.' },
  { id: 2, name: 'Juror #2', age: 34, occupation: 'Civil Engineer', background: 'Works on infrastructure projects, analytical thinker.' },
  { id: 3, name: 'Juror #3', age: 42, occupation: 'Elementary School Teacher', background: 'Works with children daily, values clear communication.' },
  { id: 4, name: 'Juror #4', age: 28, occupation: 'Software Developer', background: 'Logical problem solver, prefers evidence-based conclusions.' },
  { id: 5, name: 'Juror #5', age: 61, occupation: 'Retired Accountant', background: 'Detail-oriented, follows rules carefully.' },
  { id: 6, name: 'Juror #6', age: 39, occupation: 'Nurse', background: 'Works in emergency room, accustomed to high-pressure decisions.' },
  { id: 7, name: 'Juror #7', age: 47, occupation: 'Construction Manager', background: 'Oversees large projects, values practical outcomes.' },
  { id: 8, name: 'Juror #8', age: 31, occupation: 'Graphic Designer', background: 'Creative professional, looks at situations from multiple angles.' },
  { id: 9, name: 'Juror #9', age: 53, occupation: 'Police Officer', background: 'Law enforcement experience, understands legal procedures.' },
  { id: 10, name: 'Juror #10', age: 45, occupation: 'Real Estate Agent', background: 'Negotiates daily, values clear terms and agreements.' },
  { id: 11, name: 'Juror #11', age: 37, occupation: 'Chef', background: 'Runs a restaurant kitchen, makes quick decisions under pressure.' },
  { id: 12, name: 'Juror #12', age: 58, occupation: 'Bank Manager', background: 'Financial professional, risk-averse and methodical.' },
  { id: 13, name: 'Juror #13', age: 29, occupation: 'Journalist', background: 'Investigates stories, questions assumptions.' },
  { id: 14, name: 'Juror #14', age: 44, occupation: 'Electrician', background: 'Trade professional, practical problem solver.' },
  { id: 15, name: 'Juror #15', age: 52, occupation: 'Social Worker', background: 'Works with diverse populations, empathetic listener.' },
  { id: 16, name: 'Juror #16', age: 35, occupation: 'Marketing Manager', background: 'Analyzes consumer behavior, persuasion-aware.' },
  { id: 17, name: 'Juror #17', age: 48, occupation: 'Pharmacist', background: 'Medical professional, values scientific evidence.' },
  { id: 18, name: 'Juror #18', age: 33, occupation: 'Mechanic', background: 'Diagnoses problems methodically, hands-on thinker.' },
  { id: 19, name: 'Juror #19', age: 56, occupation: 'Librarian', background: 'Information specialist, thorough researcher.' },
  { id: 20, name: 'Juror #20', age: 41, occupation: 'Truck Driver', background: 'Independent worker, values honesty and directness.' },
  { id: 21, name: 'Juror #21', age: 30, occupation: 'Yoga Instructor', background: 'Wellness professional, calm and reflective.' },
  { id: 22, name: 'Juror #22', age: 49, occupation: 'Architect', background: 'Designs buildings, thinks structurally and systematically.' },
  { id: 23, name: 'Juror #23', age: 38, occupation: 'Flight Attendant', background: 'Service industry, experienced with conflict resolution.' },
  { id: 24, name: 'Juror #24', age: 54, occupation: 'Insurance Agent', background: 'Risk assessor, evaluates probability and liability.' },
  { id: 25, name: 'Juror #25', age: 32, occupation: 'Personal Trainer', background: 'Motivational, focused on goals and outcomes.' },
  { id: 26, name: 'Juror #26', age: 46, occupation: 'Veterinarian', background: 'Medical professional, compassionate decision maker.' },
  { id: 27, name: 'Juror #27', age: 36, occupation: 'HR Manager', background: 'Handles workplace disputes, fair-minded.' },
  { id: 28, name: 'Juror #28', age: 50, occupation: 'Plumber', background: 'Trade professional, solves problems efficiently.' },
  { id: 29, name: 'Juror #29', age: 27, occupation: 'Data Analyst', background: 'Works with statistics, evidence-driven mindset.' },
  { id: 30, name: 'Juror #30', age: 43, occupation: 'Salesperson', background: 'Reads people well, understands persuasion tactics.' },
  { id: 31, name: 'Juror #31', age: 57, occupation: 'Museum Curator', background: 'Preserves history, values authenticity and accuracy.' },
  { id: 32, name: 'Juror #32', age: 40, occupation: 'Firefighter', background: 'Emergency responder, makes critical decisions quickly.' },
  { id: 33, name: 'Juror #33', age: 26, occupation: 'Barista', background: 'Service worker, interacts with diverse people daily.' },
  { id: 34, name: 'Juror #34', age: 51, occupation: 'Tax Preparer', background: 'Detail-focused, follows regulations carefully.' },
  { id: 35, name: 'Juror #35', age: 39, occupation: 'Photographer', background: 'Visual thinker, observes details others miss.' },
  { id: 36, name: 'Juror #36', age: 45, occupation: 'Postal Worker', background: 'Government employee, reliable and punctual.' },
  { id: 37, name: 'Juror #37', age: 33, occupation: 'Event Planner', background: 'Organizes complex logistics, thinks ahead.' },
  { id: 38, name: 'Juror #38', age: 59, occupation: 'Counselor', background: 'Mental health professional, listens carefully.' },
  { id: 39, name: 'Juror #39', age: 37, occupation: 'Carpenter', background: 'Craftsperson, precise and methodical.' },
  { id: 40, name: 'Juror #40', age: 48, occupation: 'IT Support Specialist', background: 'Troubleshooter, systematic problem solver.' },
  { id: 41, name: 'Juror #41', age: 31, occupation: 'Physical Therapist', background: 'Healthcare provider, patient-focused.' },
  { id: 42, name: 'Juror #42', age: 53, occupation: 'Bus Driver', background: 'Transportation professional, responsible and alert.' },
  { id: 43, name: 'Juror #43', age: 28, occupation: 'Lab Technician', background: 'Scientific worker, values precision and testing.' },
  { id: 44, name: 'Juror #44', age: 44, occupation: 'Restaurant Manager', background: 'Oversees operations, handles pressure well.' },
  { id: 45, name: 'Juror #45', age: 35, occupation: 'Paralegal', background: 'Legal support staff, familiar with court procedures.' },
  { id: 46, name: 'Juror #46', age: 56, occupation: 'Delivery Driver', background: 'Independent worker, navigates challenges daily.' },
  { id: 47, name: 'Juror #47', age: 41, occupation: 'Customer Service Rep', background: 'Handles complaints, seeks fair resolutions.' },
  { id: 48, name: 'Juror #48', age: 34, occupation: 'Security Guard', background: 'Vigilant observer, protective instinct.' },
  { id: 49, name: 'Juror #49', age: 49, occupation: 'Landscaper', background: 'Outdoor worker, patient and detail-oriented.' },
  { id: 50, name: 'Juror #50', age: 38, occupation: 'Bookkeeper', background: 'Financial recordkeeper, organized and accurate.' },
];

export function getRandomJurors(count: number = 12): Juror[] {
  const shuffled = [...JURY_POOL].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
